import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import Footer from "@/components/Footer/Footer";
import { Montserrat, Raleway } from "next/font/google";

const mont = Montserrat({
  weight: "400",
  subsets: ["latin", "latin-ext"],
  variable: "--font-mont",
});

const openSans = Raleway({
  weight: ["400", "700"],
  subsets: ["latin", "latin-ext"],
  variable: "--font-opensans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${mont.variable} ${openSans.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
